### PR TITLE
Feature/backend-and-frontend-service

### PR DESCRIPTION
**Pull request by retrokiller543**
# Backend Service

Currently i have setup the backend service to build with the dev profile meaning its a lot less intense to compile and build the image. 

The service also currently has a health check that wont work since wget is not installed in the image, i will fix this with the next wave of changes to the backend.

# Frontend Service

Since the frontend already had a dockerfile ready in the main branch i decided to add the service for it when i already was doing things in here.

There is nothing special about this service at the moment other than its running on the same network as backend.

# Networks and exposed services

We need to remeber to not expose ports of the main DB in the future, it will run only inside docker and not be exposed outside, the only reason to have it like this at the moment is to make development easier.

### CODE REVIEW

**Comment by writemorecode** [comment]
Running "docker compose build" after a clean clone and checkout of this PR, I get the following error:

```
> [frontend builder 4/5] RUN bun install:
0.196 bun install v1.1.29 (6d43b366)
0.208 Resolving dependencies
1.030 Resolved, downloaded and extracted [12]
1.042 error: ENOENT installing sdk (opening cache/package/version dir)
2.678 Saved lockfile
2.678
2.678 + @rushstack/eslint-patch@1.10.4
2.678 + @tsconfig/node20@20.1.4
2.678 + @types/node@22.6.1
2.678 + @vitejs/plugin-vue@5.1.3
2.678 + @vue/eslint-config-prettier@9.0.0
2.678 + @vue/eslint-config-typescript@13.0.0
2.678 + @vue/tsconfig@0.5.1
2.678 + eslint@8.57.0
2.678 + eslint-plugin-vue@9.28.0
2.679 + npm-run-all2@6.2.2
2.679 + prettier@3.3.3
2.679 + typescript@5.6.2
2.679 + vite@5.4.5
2.679 + vite-plugin-vue-devtools@7.4.5
2.679 + vue-tsc@2.1.6
2.679 + pinia@2.2.2
2.679 + vite-plugin-wasm@3.3.0
2.679 + vue@3.5.4
2.679 + vue-router@4.4.5
2.679
2.679 315 packages installed [2.50s]
2.679 Failed to install 1 package
------
failed to solve: process "/bin/sh -c bun install" did not complete successfully: exit code: 1
```

**Comment by retrokiller543** [comment]
> Running "docker compose build" after a clean clone and checkout of this PR, I get the following error:
> 
> ```
> > [frontend builder 4/5] RUN bun install:
> 0.196 bun install v1.1.29 (6d43b366)
> 0.208 Resolving dependencies
> 1.030 Resolved, downloaded and extracted [12]
> 1.042 error: ENOENT installing sdk (opening cache/package/version dir)
> 2.678 Saved lockfile
> 2.678
> 2.678 + @rushstack/eslint-patch@1.10.4
> 2.678 + @tsconfig/node20@20.1.4
> 2.678 + @types/node@22.6.1
> 2.678 + @vitejs/plugin-vue@5.1.3
> 2.678 + @vue/eslint-config-prettier@9.0.0
> 2.678 + @vue/eslint-config-typescript@13.0.0
> 2.678 + @vue/tsconfig@0.5.1
> 2.678 + eslint@8.57.0
> 2.678 + eslint-plugin-vue@9.28.0
> 2.679 + npm-run-all2@6.2.2
> 2.679 + prettier@3.3.3
> 2.679 + typescript@5.6.2
> 2.679 + vite@5.4.5
> 2.679 + vite-plugin-vue-devtools@7.4.5
> 2.679 + vue-tsc@2.1.6
> 2.679 + pinia@2.2.2
> 2.679 + vite-plugin-wasm@3.3.0
> 2.679 + vue@3.5.4
> 2.679 + vue-router@4.4.5
> 2.679
> 2.679 315 packages installed [2.50s]
> 2.679 Failed to install 1 package
> ------
> failed to solve: process "/bin/sh -c bun install" did not complete successfully: exit code: 1
> ```

There are instructions to compile the sdk, follow the instructions in the readme, they might be slightly unclear but all information is in it.

**Comment by writemorecode** [comment]
Ok, that fixed the problem. Should this step be added to the build process?

**Comment by retrokiller543** [comment]
We could add it bit that would require us to install rust and wasm-pack inte the build step, not sure if we want that but we might

**Review by writemorecode — APPROVED** [review]

**Review by muaathaw — APPROVED** [review]

**Pull request merged**
